prometheus:
  alertmanager:
    config:
      global:
        smtp_smarthost: 'smtp.example.com:587'
        smtp_from: 'alertmanager@example.com'
        smtp_auth_username: 'user@example.com'
        smtp_auth_password: 'password'
      route:
        receiver: 'email-alert'
      receivers:
        - name: 'email-alert'
          email_configs:
            - to: 'your-email@example.com'
